# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '14.5'

pod 'SwiftLint'

target 'TVMazeApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TVMazeApp

  target 'TVMazeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TVMazeAppUITests' do
    # Pods for testing
  end

end
